name: iOS production build and submit

on:
  push:
    branches: ['main']

jobs:
  build_ios:
    name: Build iOS
    type: build
    params:
      platform: ios
      profile: production
  submit_ios:
    name: Submit to App Store
    type: submit
    needs: [build_ios]
    params:
      platform: ios
      build_id: ${{ needs.build_ios.outputs.build_id }}
      profile: production
